### ISSUE TITLE
Doesn't compile on Node 12

### ISSUE THREAD

**Issue by pdufour** [gaoxiangxyz/ed25519#1]
Hi! it seems like you have the most up to date fork of ed25519. I was looking at using this library because I'm having trouble with the native crypto resource. Unfortunately it doesn't compile on Node 12:

```
./src/ed25519.cc:19:89: error: no matching member function for call to 'ToObject'
        if ((info.Length() < 1) || (!Buffer::HasInstance(info[0])) || (Buffer::Length(info[0]->ToObject()) != 32)) {
```

**Comment by gaoxiangxyz** [comment]
you can try [this](https://github.com/canonchain/ed25519-wasm) which build c code to wasm. It should be working for node12 although it is not tested. And we may test it on node12 later.
